language: c
install:
  - curl -O http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - tar xfz rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - (cd rust-nightly-x86_64-unknown-linux-gnu/ && sudo ./install.sh)
  - cd ../
  - git clone --recursive https://github.com/rust-lang/cargo
  - (cd cargo && sudo make install)
script:
  - cargo build
  - cargo test
