language: c
install:
  - curl -O http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - tar xfz rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - (cd rust-nightly-x86_64-unknown-linux-gnu/ && sudo ./install.sh)
  - export LD_LIBRARY_PATH=/usr/local/lib
  - cd ../
  - git clone --recursive https://github.com/rust-lang/cargo
  - (cd cargo && make -j5 && sudo make install)
  - cd rustpy
script:
  - cargo build
  - cargo test
  - rustdoc src/rustpy.rs
